---
name: Lint
permissions:
  contents: read
  pull-requests: read

on:
  workflow_call:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/setup-go@v4
        with:
          cache: false
          go-version: '1.20'
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout 4m  --skip-dirs=thirdparty --skip-dirs=vendor
          version: v1.52
          skip-cache: true
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
