---
name: Scanner - Vuln

on:
  workflow_call:

jobs:
  run:
    name: Vuln
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          cache: false
          go-version: 'stable'
          check-latest: true

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck
        run: govulncheck -test ./...
