---
name: Test and Build Go

on:
  workflow_call:
    inputs:
      publish_container:
        description: "Create and Publish container"
        default: false
        type: boolean
    secrets:
      snyk_token:
        description: "Snyk Authentication Token"
        required: true
      artifactory_username:
        description: "Username for Helm and Docker registry"
        required: true
      artifactory_password:
        description: "Password for Helm and Docker registry"
        required: true
      cosign_gcp_workload_identity_provider:
        description: "Google Cloud Workload Identity Provider"
        required: true
      cosign_gcp_service_account:
        description: "Google Cloud Service Account"
        required: true


jobs:
  changed_source:
    uses: ./.github/workflows/changed-source.yml

  gosec:
    needs: changed_source
    if: ${{ needs.changed_source.outputs.changed }}
    uses: ./.github/workflows/go-gosec.yml

  lint:
    needs: changed_source
    if: ${{ needs.changed_source.outputs.changed }}
    uses: ./.github/workflows/go-lint.yml

  snyk:
    needs: changed_source
    if: ${{ needs.changed_source.outputs.changed }}
    uses: ./.github/workflows/go-snyk.yml
    secrets:
      snyk_token: ${{ secrets.snyk_token }}

  test:
    needs: changed_source
    if: ${{ needs.changed_source.outputs.changed }}
    uses: ./.github/workflows/go-test.yml

  vuln:
    needs: changed_source
    if: ${{ needs.changed_source.outputs.changed }}
    uses: ./.github/workflows/go-vuln.yml

  status:
    needs: changed_source
    if: ${{ needs.changed_source.outputs.changed }}
    uses: ./.github/workflows/branch-status.yml

  publish:
    if: ${{
          github.event.pull_request.merged == true &&
          (
              github.event.pull_request.base.ref == 'main' ||
              github.event.pull_request.base.ref == 'dev' ||
              github.event.pull_request.base.ref == 'test' ||
              startsWith(github.event.pull_request.base.ref, 'release/')
          ) &&
          needs.changed_source.outputs.changed &&
          inputs.publish_container == true
        }}
    needs: [gosec, lint, snyk, status, test, vuln]
    uses: ./.github/workflows/publish-container.yml
    with:
      status: ${{ needs.status.outputs.status }}
    secrets:
      artifactory_username: ${{ secrets.artifactory_username }}
      artifactory_password: ${{ secrets.artifactory_password }}
      cosign_gcp_workload_identity_provider: ${{ secrets.cosign_gcp_workload_identity_provider }}
      cosign_gcp_service_account: ${{ secrets.cosign_gcp_service_account }}
